anyproto/anytype-ts

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md, .github/workflows/cla.yml, .gitignore, README.md, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/SECURITY.md
This PR adds docs and github tooling to make contributing possible
https://linear.app/anytype/issue/OPEN-23/prepare-anytype-ts-for-external-contributions
https://github.com/orgs/anyproto/discussions/23
https://github.com/orgs/anyproto/discussions/9
none
----
=> Make contributing possible

package.json
- closes #101
I'll remove the `lint` script for now. I will replace it with a proper one as I open a PR for #78.
=> fix: closes #101

.github/workflows/mirror-text.yml
---
---
This PR Fixes the [mirror-text](https://github.com/anyproto/anytype-ts/blob/ae78d791d480ef84619a3767ea6691dfba8b2908/.github/workflows/mirror-text.yml) GitHub workflow unnecessarily running on forked repositories.
- Continuation of #141
*None*
*None*
=> Prevent unnecessary Github workflow triggers in forked repositories

js-anytype.code-workspace, package-lock.json, package.json
---
---
Previous attempts to properly make use of existing linters and formatters were unsuccessful due to:
1. It not being able to work properly without making changes to the entire codebase
2. It not respecting existing code style
As such, all linting and formatting related features were subsequently disabled. And if they are not being used, I don't see any reason for keeping them around. Especially because some IDEs automatically pick up linter and formatter configs and make changes accordingly by default (or are configured to do so).
So this PR removes all of them.
*None*
*None*
=> Remove unused linters & formatters

src/json/text.json, src/ts/component/block/dataview.tsx, src/ts/component/block/type.tsx, src/ts/component/menu/block/add.tsx, src/ts/component/menu/block/more.tsx, src/ts/component/menu/dataview/template.tsx, src/ts/component/page/main/type.tsx, src/ts/component/popup/template.tsx
=> Feature/JS-2556: Templates analytics

src/ts/component/block/dataview.tsx, src/ts/component/menu/dataview/context.tsx, src/ts/component/page/main/archive.tsx, src/ts/component/page/main/graph.tsx, src/ts/component/page/main/set.tsx, src/ts/component/popup/page/settings/space/storage.tsx, src/ts/component/util/toast.tsx, src/ts/lib/action.ts
=> code review

src/ts/component/menu/block/latex.tsx, src/ts/component/menu/preview/latex.tsx
---
---
https://community.anytype.io/t/latex-not-rendering-ce
Previously:
Fixed:
=> Fix chemical equations in LaTeX preview

src/ts/component/block/table.tsx
---
---
https://anytypeio.slack.com/archives/C03TF77MEHL/p1691599534188669
=> Fix lang variable blockTableHeaderRow

package.json, tsconfig.json
Reverts anyproto/anytype-ts#179
=> Revert "Fix lint-staged"

src/ts/component/menu/relation/suggest.tsx, src/ts/store/menu.ts
=> JS-2788: fix

src/ts/component/widget/index.tsx
---
---
https://github.com/anyproto/anytype-ts/issues/189
=> Fix Widget toggle animation

src/ts/component/popup/page/settings/import/csv.tsx, src/ts/component/popup/page/settings/import/index.tsx, src/ts/component/popup/page/settings/import/markdown.tsx, src/ts/component/popup/page/settings/import/notion/warning.tsx, src/ts/component/popup/settings.tsx, src/ts/interface/popup.ts, src/ts/lib/action.ts
=> Import electron dialog refactoring

src/ts/component/popup/page/settings/import/csv.tsx
---
---
Fix missing import that leads to build fail
*None*
*None*
=> fix missing import

src/json/text.json, src/scss/popup/settings.scss, src/ts/component/popup/page/settings/import/notion.tsx
=> Feature/JS-2793: Import from notion screen update

src/json/text.json
https://crowdin.com/translate/anytype-desktop/all/en-de?filter=basic&value=0#5155
=> Update right arrow symbols

README.md
---
---
Adds additional instructions on setting up the developer environment for the project
=> Add instructions to install jq, as running ./update.sh does not work unless installed

src/ts/component/block/dataview/cell/object.tsx, src/ts/component/editor/page.tsx, src/ts/component/form/input.tsx, src/ts/lib/focus.ts, src/ts/lib/keyboard.ts, src/ts/lib/util/common.ts
=> JS-2856: Escape popup close check

src/ts/component/block/text.tsx, src/ts/component/page/main/usecase.tsx, src/ts/component/util/graph.tsx, src/ts/lib/mark.ts, src/ts/store/block.ts
=> Bugfix/JS-2872: Unicode markup

src/ts/component/menu/block/add.tsx
---
---
Activate option to create object when searching for an object to link to
https://community.anytype.io/t/creating-new-objects-from-the-link-to-object-ui/7059/3
=> "add" option when search on "link to object"

src/ts/component/editor/page.tsx, src/ts/component/page/main/history.tsx, src/ts/lib/action.ts, src/ts/store/block.ts
=> JS-2879: History copy

src/ts/component/menu/block/more.tsx, src/ts/component/page/main/archive.tsx, src/ts/component/popup/page/settings/space/storage.tsx, src/ts/lib/action.ts
=> Refactoring delete

src/scss/block/text.scss, src/scss/media/print.scss, src/ts/component/block/text.tsx
=> #206: fix code formatting

src/ts/lib/storage.ts, src/ts/lib/survey.ts
=> Bugfix/JS-2882: Survey logic update and refactoring

src/json/text.json
---
---
Correct the text for the button "Settings" on dataview
(before, it was "Sort", same as Sort button next to it)
None, I hope it's not necessary for something like that?
No
=> Correcting default text for dataview settings

src/scss/theme/dark/menu.scss, src/ts/component/menu/block/more.tsx, src/ts/component/menu/dataview/template/context.tsx, src/ts/component/page/main/type.tsx
=> Feature/JS-2556: Template option analytics

src/ts/component/menu/block/link.tsx
=> Feature/JS-2867: Order of link url action

src/json/text.json, src/scss/component/footer.scss, src/scss/page/auth.scss, src/ts/component/footer/auth/disclaimer.tsx, src/ts/component/footer/index.tsx, src/ts/component/page/auth/select.tsx
=> Feature/JS-2851: Auth disclaimer

src/json/text.json
=> Copy fix: 'Commit to OUR terms...'

src/json/text.json, src/ts/component/menu/block/more.tsx
=> Feature/JS-2918: Toast on set default template

src/scss/component/toast.scss, src/ts/lib/preview.ts
=> Feature/JS-2927: Toast position

src/json/text.json, src/scss/component/header.scss, src/ts/component/header/main/object.tsx
=> Feature/JS-2797: Restore button in bin banner

src/scss/menu/dataview/template.scss, src/ts/component/block/dataview.tsx, src/ts/component/block/dataview/controls.tsx, src/ts/component/menu/dataview/template/context.tsx, src/ts/component/menu/dataview/template/list.tsx, src/ts/component/menu/dataview/view/settings.tsx, src/ts/component/menu/index.tsx, src/ts/interface/block/dataview.ts, src/ts/lib/api/command.ts, src/ts/lib/util/object.ts
=> Refactoring templates

src/json/text.json, src/scss/component/sidebar.scss, src/scss/widget/list.scss, src/ts/component/block/dataview.tsx, src/ts/component/menu/block/link/settings.tsx, src/ts/component/menu/block/relation/edit.tsx, src/ts/component/menu/dataview/filter/list.tsx, src/ts/component/menu/dataview/object/values.tsx, src/ts/component/menu/index.tsx, src/ts/component/menu/relation/suggest.tsx, src/ts/component/sidebar/index.tsx, src/ts/component/widget/list/index.tsx, src/ts/component/widget/list/item.tsx, src/ts/lib/relation.ts
=> Favorites drag and drop

src/ts/component/block/dataview.tsx, src/ts/component/menu/dataview/template/list.tsx, src/ts/component/menu/dataview/view/settings.tsx, src/ts/component/page/main/type.tsx, src/ts/lib/api/command.ts, src/ts/lib/util/object.ts
=> default template logic

src/ts/component/block/dataview/head.tsx
=> JS-2585: Inline set caret

src/ts/component/block/dataview/cell/object.tsx, src/ts/component/block/dataview/cell/select.tsx
=> JS-2868: Relation entry caret

src/ts/component/block/featured.tsx, src/ts/component/menu/onboarding.tsx, src/ts/docs/help/onboarding.ts
=> Feature/JS-2975: Change deleted type

src/json/constant.json, src/ts/component/block/table.tsx
=> JS-2992: fix

src/scss/block/dataview/cell.scss, src/ts/component/block/dataview/cell/text.tsx
=> JS-2993: fix

src/ts/component/block/dataview/controls.tsx, src/ts/component/menu/dataview/view/list.tsx, src/ts/lib/util/menu.ts
=> Feature/JS-3070: View context menu refactoring

src/scss/component/iconObject.scss, src/ts/component/block/index.tsx, src/ts/component/menu/block/more.tsx, src/ts/component/menu/space.tsx, src/ts/component/page/auth/onboard.tsx, src/ts/component/page/main/empty.tsx, src/ts/component/popup/page/settings/space/create.tsx, src/ts/component/popup/page/settings/space/index.tsx, src/ts/component/util/iconObject.tsx, src/ts/component/widget/space.tsx, src/ts/interface/account.ts, src/ts/interface/block.ts, src/ts/interface/object.ts, src/ts/lib/api/command.ts, src/ts/lib/api/mapper.ts, src/ts/lib/api/response.ts, src/ts/lib/util/data.ts, src/ts/lib/util/object.ts, src/ts/lib/util/router.ts, src/ts/model/account.ts, src/ts/model/block.ts, src/ts/store/block.ts, src/ts/store/detail.ts
=> JS-3086: Space view update

src/json/constant.json, src/ts/component/block/text.tsx
---
---
Enables Nix programming language highlighting.
https://linear.app/anytype/issue/PBI-313/nix-programming-language-integration-for-code-snippets-feature
https://community.anytype.io/t/nix-programming-language-integration-for-code-snippets/8475
=> Enable nix highlighting

src/ts/component/menu/dataview/object/list.tsx, src/ts/lib/action.ts, src/ts/lib/api/response.ts, src/ts/lib/util/object.ts
=> Fix legacy import

src/json/text.json, src/ts/component/menu/dataview/filter/list.tsx
---
---
This PR adds localization for "New filter" used in sets and collections.
=> Adding localization of "New filter"

src/ts/component/block/dataview.tsx, src/ts/component/block/index.tsx, src/ts/component/editor/page.tsx, src/ts/component/menu/block/more.tsx, src/ts/component/page/main/block.tsx, src/ts/component/page/main/media.tsx, src/ts/component/page/main/relation.tsx, src/ts/component/page/main/set.tsx, src/ts/component/page/main/type.tsx, src/ts/component/preview/object.tsx, src/ts/component/widget/list/index.tsx, src/ts/interface/block.ts, src/ts/lib/action.ts, src/ts/lib/api/command.ts, src/ts/lib/util/data.ts, src/ts/lib/util/object.ts, src/ts/model/block.ts, src/ts/store/detail.ts
=> Bugfix/JS-3172: Dates

src/scss/menu/dataview/template.scss, src/ts/component/list/previewObject.tsx, src/ts/component/menu/dataview/template/list.tsx
=> Refactoring/JS-3176: Template fixes

src/json/constant.json, src/ts/component/block/dataview.tsx, src/ts/component/menu/space.tsx, src/ts/lib/util/data.ts, src/ts/store/detail.ts
=> Space local status filter

src/json/text.json
Checked it w Kostya Mordan - fyi latest texts are on mobile, can be found here: 
https://linear.app/anytype/issue/IOS-1717/update-login-texts-and-design
---
---
=> Updated login > recovery phrase description to match mobile text

src/scss/theme/dark/common.scss
=> fix: set correct color-scheme on dark

src/scss/page/auth.scss, src/ts/component/form/button.tsx, src/ts/component/page/auth/login.tsx, src/ts/component/popup/page/settings/delete.tsx, src/ts/component/widget/index.tsx
=> Feature/JS-3263: Auth rework

dist/workers/graph.js, src/ts/component/block/dataview/view/grid.tsx, src/ts/component/block/dataview/view/list.tsx, src/ts/lib/survey.ts
=> JS-3269: Add row in inline sets

src/json/text.json, src/scss/popup/settings.scss, src/ts/component/popup/page/settings/personal.tsx, src/ts/component/popup/page/settings/space/index.tsx, src/ts/lib/storage.ts
=> Feature/JS-3288: Default type in space settings

src/img/icon/notification/delete.svg, src/json/constant.json, src/json/text.json, src/scss/component/footer.scss, src/scss/component/headSimple.scss, src/scss/notification/common.scss, src/ts/app.tsx, src/ts/component/block/dataview.tsx, src/ts/component/index.tsx, src/ts/component/list/notification.tsx, src/ts/component/notification/index.tsx, src/ts/component/notification/invite.tsx, src/ts/component/notification/usecase.tsx, src/ts/component/page/index.tsx, src/ts/interface/index.ts, src/ts/interface/notification.ts, src/ts/model/index.ts, src/ts/model/notification.ts, src/ts/store/index.ts, src/ts/store/menu.ts, src/ts/store/notification.ts
=> Feature/JS-3304: Notifications

src/ts/component/menu/dataview/view/layout.tsx, src/ts/component/menu/dataview/view/settings.tsx, src/ts/lib/dataview.ts
=> Refactoring/JS-3348: Default view name

src/json/text.json, src/ts/component/menu/onboarding.tsx, src/ts/docs/help/onboarding.ts
=> Feature/JS-3314: Wizard updates

src/scss/page/main/navigation.scss, src/ts/component/page/main/navigation.tsx
=> JS-2392: Navigation refactoring and fixes

src/scss/block/link.scss, src/scss/theme/dark/block.scss, src/ts/component/block/link.tsx, src/ts/component/block/text.tsx
=> JS-3335: add undeline to link name

src/ts/component/menu/block/relation/edit.tsx, src/ts/component/menu/block/relation/view.tsx
=> JS-3368: fix readonly flag in bin

src/ts/component/form/select.tsx, src/ts/component/menu/dataview/filter/values.tsx, src/ts/component/menu/dataview/view/settings.tsx, src/ts/component/menu/index.tsx, src/ts/component/menu/select.tsx
=> Feature/JS-2460: Filter values hover

electron/js/preload.js, src/ts/app.tsx, src/ts/component/block/help/text.tsx, src/ts/component/form/button.tsx, src/ts/component/menu/item/vertical.tsx, src/ts/component/page/auth/login.tsx, src/ts/component/popup/page/settings/import/notion/warning.tsx, src/ts/component/popup/shortcut.tsx, src/ts/component/util/emptySearch.tsx, src/ts/component/util/error.tsx, src/ts/component/util/label.tsx, src/ts/component/util/title.tsx, src/ts/component/util/toast.tsx, src/ts/lib/util/common.ts
=> JS-3405: Security update

src/ts/component/widget/index.tsx, src/ts/lib/storage.ts, src/ts/lib/util/data.ts
=> Feature/JS-2980: Creation with link bugfix + sort by last used fix

src/scss/form/button.scss, src/ts/component/popup/confirm.tsx
=> Feature/JS-3270: Keyboard logic in popup confirm

electron/json/cors.json, src/json/text.json, src/ts/component/block/embed.tsx, src/ts/interface/block/embed.ts, src/ts/lib/util/embed.ts, src/ts/lib/util/menu.ts
=> Feature/JS-3342: Google maps embed

electron/json/cors.json, src/ts/component/block/embed.tsx, src/ts/interface/block/embed.ts, src/ts/lib/util/embed.ts, src/ts/lib/util/menu.ts
=> Feature/JS-3373: Miro embed

src/ts/component/block/table.tsx, src/ts/component/block/table/cell.tsx, src/ts/interface/block/table.ts
=> Bugfix/JS-1943: Update table frame

src/ts/component/block/text.tsx, src/ts/component/form/filter.tsx, src/ts/component/menu/block/action.tsx, src/ts/component/menu/dataview/file/list.tsx, src/ts/component/menu/dataview/option/list.tsx, src/ts/component/menu/index.tsx, src/ts/component/menu/quickCapture.tsx, src/ts/component/menu/relation/suggest.tsx, src/ts/component/menu/search/object.tsx, src/ts/component/menu/select.tsx, src/ts/component/menu/smile.tsx, src/ts/component/menu/type/suggest.tsx, src/ts/lib/util/smile.ts
=> Feature/JS-2193: Remove mentions and emojis on backspace, refactoring

src/scss/form/button.scss, src/scss/theme/dark/common.scss, src/ts/component/popup/confirm.tsx
=> Feature/JS-3270: Buttons in confirm style fix

src/json/constant.json, src/json/text.json, src/ts/component/list/notification.tsx, src/ts/component/notification/export.tsx, src/ts/component/notification/import.tsx, src/ts/component/notification/index.tsx, src/ts/component/notification/invite.tsx, src/ts/component/notification/usecase.tsx, src/ts/interface/index.ts, src/ts/interface/notification.ts, src/ts/lib/api/command.ts, src/ts/lib/api/dispatcher.ts, src/ts/lib/api/mapper.ts, src/ts/lib/api/response.ts, src/ts/lib/util/data.ts, src/ts/model/notification.ts, src/ts/store/notification.ts
=> Feature/JS-3349: Notifications

src/json/text.json, src/ts/component/notification/gallery.tsx, src/ts/component/notification/index.tsx, src/ts/interface/notification.ts, src/ts/lib/api/mapper.ts
=> Feature/JS-3468: Gallery notification

src/ts/component/form/phrase.tsx, src/ts/component/page/auth/login.tsx, src/ts/lib/api/dispatcher.ts, src/ts/lib/storage.ts, src/ts/lib/util/object.ts, src/ts/store/db.ts
=> Refactoring/JS-3401: Phrase input

package-lock.json, package.json
=> Update/JS-3607: fix

src/ts/component/menu/smile.tsx
---
---
The scroll bar affects the width of the icons, so I fill the unfilled rows with blank elements to keep the width of the icons consistent with the other rows.
**before**
**↓↓↓↓↓**
**after**
**↓↓↓↓↓**
=> fill the unfilled row with blank elements.

src/ts/component/menu/smile.tsx
---
---
The old style neglected the width of the scrollbar, causing the icons to be compressed to a certain extent and unable to align properly.
**before**
↓↓↓↓↓
**after**
↓↓↓↓↓
=> style: change smile's width

src/scss/menu/dataview/option.scss, src/ts/component/block/dataview/cell/index.tsx, src/ts/component/block/dataview/cell/select.tsx, src/ts/component/util/tag.tsx, src/ts/interface/block/dataview.ts
=> Feature/JS-3670: Edit options on right click

electron/about/about.css
=> #426: fix styles

src/ts/component/block/text.tsx, src/ts/component/editor/page.tsx, src/ts/component/menu/block/link.tsx, src/ts/lib/util/common.ts
=> Feature/JS-3644: Paste local link

src/ts/component/form/filter.tsx, src/ts/component/form/inputWithFile.tsx, src/ts/component/page/main/store.tsx
---
---
some text fields run translate function before the app get the `interfaceLang` value,  and they have not been updated.
I know this is not the best way to modify, but this modification has a relatively small impact on the code.
#435
=> fix: translate error

src/scss/block/embed.scss, src/scss/block/media.scss, src/ts/component/block/embed.tsx, src/ts/component/block/media/pdf.tsx, src/ts/component/block/media/video.tsx, src/ts/model/block.ts
=> Feature/JS-3534: Embed blocks resize

src/ts/component/block/text.tsx, src/ts/component/editor/page.tsx, src/ts/component/menu/search/object.tsx
=> Bugfix/JS-3453: Paste url and type text problem

dist/workers/graph.js
=> Bugfix/JS-3684: Orphan nodes filtering

dist/embed/iframe.html, electron/json/cors.json, src/scss/block/embed.scss, src/ts/component/block/dataview/view/board.tsx, src/ts/component/block/embed.tsx, src/ts/component/block/media/video.tsx, src/ts/interface/block/embed.ts, src/ts/lib/util/embed.ts, src/ts/lib/util/menu.ts
=> Feature/JS-3477: Embeds

src/scss/block/text.scss, src/ts/component/block/text.tsx, src/ts/component/menu/search/text.tsx, src/ts/lib/mark.ts, src/ts/lib/util/common.ts
=> Refactoring/JS-3587: Markup tags

src/scss/block/dataview/cell.scss, src/scss/block/dataview/view/board.scss, src/scss/block/dataview/view/common.scss, src/scss/block/featured.scss, src/scss/block/relation.scss, src/scss/menu/block/relation.scss, src/scss/menu/dataview/option.scss, src/scss/theme/dark/common.scss
=> Refactoring/JS-3682: Relation style

electron/json/cors.json, src/ts/interface/block/embed.ts, src/ts/lib/util/embed.ts, src/ts/lib/util/menu.ts
---
---
Referring to the new code modified from the **Embed** branch, svg icons may need you to supplement.
But there is still one problem I couldn't resolve. On the mobile app of Bilibili, video sharing uses short links, and more mobile users would use these short links to embed videos, but I have no clue how to parse out the final URL in the browser environment.
Some test links here:
- `https://www.bilibili.com/video/BV1mp4y1E7us/`
- `https://b23.tv/0tFYDoo`
#441
=> append bilibili embed

src/ts/lib/util/menu.ts
---
---
Use the English names of menu block names as aliases for other languages.
#451
=> update block menu's aliases

src/ts/component/form/editable.tsx, src/ts/lib/util/common.ts
=> Refactoring/JS-3689: Editor optimisation

src/scss/menu/smile.scss, src/ts/component/menu/smile.tsx, src/ts/lib/keyboard.ts, src/ts/lib/sidebar.ts, src/ts/lib/storage.ts, src/ts/store/common.ts
=> Refactoring/JS-3572: Sidebar

src/json/text.json, src/scss/block/text.scss, src/scss/menu/quickCapture.scss, src/scss/theme/dark/block.scss, src/scss/theme/dark/menu.scss, src/ts/component/menu/quickCapture.tsx, src/ts/component/page/auth/onboard.tsx, src/ts/lib/storage.ts, src/ts/lib/util/data.ts, src/ts/lib/util/menu.ts
=> Feature/JS-3591: Quick Capture Updates

src/ts/component/block/text.tsx
=> Prevent shortcuts in code block

src/ts/lib/util/embed.ts
---
---
[Youtube timestamps? ](https://community.anytype.io/t/youtube-timestamps/13097)
> btw,  the embedded styles in the development version are always strange.
=> Youtube support timestamp

package-lock.json, package.json, src/scss/block/embed.scss, src/scss/menu/block/common.scss, src/scss/theme/dark/block.scss, src/ts/component/block/embed.tsx, src/ts/component/util/label.tsx, src/ts/interface/block/embed.ts, src/ts/lib/util/menu.ts
=> Feature/JS-3685: Excalidraw

package-lock.json, package.json, src/scss/menu/quickCapture.scss, src/ts/component/block/dataview/controls.tsx, src/ts/component/menu/quickCapture.tsx
=> Feature/JS-3691: Pinned section DND

src/ts/component/block/link.tsx
---
---
Modify the click event type and event location of the page block.
#470
=> Improve page block's UX

src/ts/component/block/text.tsx
---
---
To provide some convenience for directly writing code in code blocks.
Also provided some additional support for full-width symbols, such as `【「(“‘` etc.
#395
=> Apply auto close braces in code block

electron/js/api.js, electron/js/preload.js, electron/js/window.js, src/ts/app.tsx, src/ts/component/block/dataview/view/board/card.tsx, src/ts/component/menu/dataview/option/edit.tsx, src/ts/lib/util/common.ts
=> Feature/Custom CSS

src/ts/component/drag/provider.tsx
=> fix drag provider coords issue

src/scss/menu/dataview/calendar.scss, src/ts/component/menu/dataview/calendar.tsx
=> Feature/JS-3407: Featured relation date design review

electron/json/cors.json, src/ts/interface/block/embed.ts, src/ts/lib/util/embed.ts, src/ts/lib/util/menu.ts
---
---
[Kroki](https://kroki.io/) is a online diagram website, the website will export a link pointing to the image(svg or png, etc).
[Please integrate WireViz into the embeds](https://community.anytype.io/t/please-integrate-wireviz-into-the-embeds/13316)
=> append kroki embed

dist/embed/iframe.html, package-lock.json, package.json, src/scss/block/embed.scss, src/ts/component/block/embed.tsx, src/ts/component/editor/page.tsx, src/ts/component/form/select.tsx, src/ts/interface/block.ts, src/ts/lib/util/common.ts, src/ts/model/block.ts
=> Kroki diagram encode

electron/json/cors.json, src/ts/component/block/embed.tsx, src/ts/interface/block/embed.ts, src/ts/lib/util/embed.ts, src/ts/lib/util/menu.ts
---
---
Automatic requests from Sentry and GoogleAds are a bit annoying, I'm not very clear on how to block this.
#492 
The default embedded field is very long, actually only part of it was used.
=> Append Sketchfab embed

src/ts/component/selection/provider.tsx, src/ts/store/detail.ts
=> Bugfix/JS-1305: Selection on scroll

src/json/text.json
https://community.anytype.io/t/typo-in-the-dialog-box-for-recovering-a-recovery-phrase/13536
---
---
=> Update recovery phrase lost text

src/img/icon/popup/space/invite.svg, src/img/theme/dark/icon/popup/space/invite.svg, src/json/text.json, src/scss/popup/common.scss, src/scss/popup/space.scss, src/scss/theme/dark/popup.scss, src/ts/app.tsx, src/ts/component/popup/about.tsx, src/ts/component/popup/index.tsx, src/ts/component/popup/space/joinRequest.tsx, src/ts/store/popup.ts
=> Feature/JS-3488: Popup request to join space

src/ts/component/block/embed.tsx
---
---
Unlike YouTube, Bilibili videos automatically play by default when `autoplay` value is unset.
=> Bilibili embed set default autoplay

src/json/text.json, src/scss/popup/space.scss, src/ts/component/notification/index.tsx, src/ts/component/popup/index.tsx, src/ts/component/popup/invite/confirm.tsx, src/ts/lib/api/command.ts, src/ts/store/popup.ts
=> Feature/JS-3487: Invite confirmation popup

src/scss/block/bookmark.scss, src/scss/block/dataview/view/board.scss, src/scss/block/dataview/view/gallery.scss, src/scss/block/embed.scss, src/scss/block/file.scss, src/scss/block/link.scss, src/scss/block/media.scss, src/scss/block/text.scss, src/scss/form/drag.scss, src/scss/form/inputWithFile.scss, src/scss/theme/dark/block.scss, src/scss/theme/dark/common.scss
=> Design/JS-3799: Border-radius fixes

src/ts/lib/mark.ts
---
---
The underscore parsing`_x_ or __x__` will only be enabled in the case of beginning or prefixing spaces.
#530
=> Modify markdown's format reg

src/ts/component/menu/search/text.tsx
---
---
Maybe remove the `.toLowerCase()` on line 152, but I think this way is also okay.
[Text with changed formatting cannot be searched](https://community.anytype.io/t/text-with-changed-formatting-cannot-be-searched/14109)
=> Modify tag filter array

src/scss/widget/common.scss, src/ts/component/widget/list/index.tsx, src/ts/component/widget/tree/index.tsx
=> Feature/JS-3222: Widget grouping design review

dist/extension/js/background.js, extension/iframe.tsx, extension/iframe/create.tsx, src/ts/component/drag/provider.tsx, src/ts/component/editor/page.tsx, src/ts/component/menu/quickCapture.tsx, src/ts/lib/api/command.ts, src/ts/store/extension.ts
=> Add url to BlockPaste and BlockPreview commands

src/scss/popup/usecase.scss, src/scss/theme/dark/popup.scss, src/ts/component/page/main/import.tsx, src/ts/component/popup/page/usecase/item.tsx, src/ts/component/popup/page/usecase/list.tsx, src/ts/component/popup/usecase.tsx, src/ts/interface/index.ts, src/ts/interface/popup.ts, src/ts/lib/api/command.ts, src/ts/lib/api/mapper.ts, src/ts/lib/api/response.ts, src/ts/lib/keyboard.ts
=> Feature/JS-3881: Usecase gallery

src/scss/block/featured.scss, src/scss/menu/common.scss, src/scss/menu/dataview/object.scss, src/scss/menu/dataview/option.scss, src/scss/menu/dataview/text.scss, src/scss/menu/dataview/view.scss, src/scss/menu/select.scss, src/ts/component/block/featured.tsx
=> Feature/JS-3935: Featured relation long text and number

README.md
---
---
The link to `anytype-heart` build instruction was broken, so I updated the link and removed unnecessary line of text in the process.
None
N/A
=> Fix broken link and make text more concise

src/scss/block/media.scss, src/ts/component/block/media/video.tsx
=> Bugfix/JS-3979: Video resize

src/json/route.json, src/ts/component/menu/block/more.tsx, src/ts/component/page/index.tsx, src/ts/component/page/main/blank.tsx, src/ts/component/page/main/object.tsx, src/ts/lib/util/object.ts
=> Feature/JS-4019: Universal deeplink

src/json/text.json
=> Small copy edits for account deletion & login screens.json

go/nativeMessagingHost.go
=> Avoid using bash on windows for getting ports

electron/js/menu.js, src/json/constant.json, src/scss/popup/settings.scss, src/ts/app.tsx, src/ts/component/form/button.tsx, src/ts/component/popup/membership.tsx, src/ts/component/popup/page/membership/paid.tsx, src/ts/component/popup/page/settings/membership.tsx, src/ts/component/popup/settings.tsx, src/ts/interface/index.ts, src/ts/interface/payment.ts, src/ts/lib/util/data.ts
=> Feature/JS-4060: Payments improvements

src/scss/page/main/edit.scss
---
---
Fix the CLS issue in the editor caused by the scroll bar.
[Unexpected sidebar popup](https://community.anytype.io/t/unexpected-sidebar-popup/16916)
=> fix: scrollbar cls

dist/challenge/index.html, electron/js/api.js, electron/js/window.js, src/ts/lib/api/dispatcher.ts
=> Electron challenge window

src/ts/component/block/dataview.tsx, src/ts/component/block/dataview/cell/index.tsx, src/ts/component/block/dataview/view/grid/body/cell.tsx, src/ts/interface/block/dataview.ts
=> Optimise canCellEdit

src/json/constant.json, src/json/text.json, src/ts/component/page/main/invite.tsx, src/ts/component/popup/invite/request.tsx, src/ts/lib/keyboard.ts
=> JS-4102, JS-4101: fix

src/ts/component/menu/quickCapture.tsx
=> Feature/JS-3989: TypeSearchResult event

src/scss/_vars.scss, src/scss/block/cover.scss, src/scss/block/dataview/view/common.scss, src/scss/block/file.scss, src/scss/component/editor.scss, src/scss/component/error.scss, src/scss/form/phrase.scss, src/scss/form/pin.scss, src/scss/menu/block/common.scss, src/scss/menu/onboarding.scss, src/scss/page/auth.scss, src/scss/page/main/store.scss, src/scss/popup/settings.scss, src/scss/widget/common.scss
=> Refactoring/JS-4119: Font-sizes moved to CSS vars

extension/lib/util.ts, package-lock.json, package.json, src/ts/lib/api/response.ts
=> Feature/JS-4115: Webclipper read-only spaces

src/ts/component/menu/block/more.tsx, src/ts/component/menu/quickCapture.tsx, src/ts/lib/action.ts
=> Feature/JS-3989: Quick capture analytics

src/json/text.json, src/ts/component/popup/settings/onboarding.tsx
=> Feature/JS-3874: Custom storage local only warning

src/ts/component/popup/page/settings/space/index.tsx, src/ts/component/popup/page/settings/space/share.tsx, src/ts/lib/util/data.ts
=> Feature/JS-4243: Shared spaces count fix

src/scss/page/main/history.scss
---
---
I assume `x` is a typo of `px`.
=> fix css typo

src/json/text.json
---
---
Refine wording of UI elements and keep it consistent with Notion:
=> refine wording of UI elements

src/json/text.json, src/scss/form/button.scss, src/scss/popup/settings.scss, src/ts/component/page/main/membership.tsx, src/ts/component/popup/membership.tsx, src/ts/component/popup/membership/finalization.tsx, src/ts/component/popup/page/membership/free.tsx, src/ts/component/popup/page/membership/paid.tsx, src/ts/component/popup/page/settings/space/index.tsx, src/ts/lib/util/data.ts, src/ts/store/popup.ts
=> Feature/JS-4186: Upgrade button for storage limit

src/ts/component/popup/membership/finalization.tsx
=> fix: finalization .any suffix (still needed)

src/json/text.json, src/ts/component/popup/page/membership/free.tsx, src/ts/store/common.ts
=> Feature/JS-4308: Email confirmation countdown

src/ts/model/membership.ts
=> payment method logics fix

src/json/text.json, src/json/url.json, src/scss/popup/membership.scss, src/scss/popup/settings.scss, src/ts/app.tsx, src/ts/component/block/featured.tsx, src/ts/component/form/button.tsx, src/ts/component/form/input.tsx, src/ts/component/menu/dataview/group/edit.tsx, src/ts/component/menu/dataview/option/edit.tsx, src/ts/component/menu/dataview/template/list.tsx, src/ts/component/page/main/store.tsx, src/ts/component/popup/page/membership/current.tsx, src/ts/component/popup/page/membership/free.tsx, src/ts/component/popup/page/membership/success.tsx, src/ts/component/popup/page/settings/membership.tsx, src/ts/component/popup/page/settings/space/index.tsx, src/ts/component/popup/page/settings/space/share.tsx, src/ts/component/widget/index.tsx, src/ts/lib/action.ts, src/ts/lib/keyboard.ts, src/ts/lib/util/common.ts
=> Feature/JS-4312: Email confirmation in Explorer current popup

src/ts/component/page/main/membership.tsx, src/ts/component/popup/membership.tsx, src/ts/component/popup/page/membership/current.tsx, src/ts/component/popup/page/membership/free.tsx, src/ts/component/popup/page/membership/paid.tsx, src/ts/lib/analytics.ts
=> Feature/JS-4208: Payment analytics fix

src/ts/component/popup/page/settings/membership.tsx
=> Feature/JS-4409: Let us know email

src/ts/component/popup/page/settings/membership.tsx, src/ts/lib/action.ts, src/ts/lib/keyboard.ts
=> Feature/JS-4409: Let us know email fix

src/json/text.json
Mostly onboarding + some typos
---
---
=> Onboarding corrections.json

src/json/text.json
=> Fix string on main screen

src/json/text.json, src/scss/menu/onboarding.scss, src/ts/component/page/auth/login.tsx, src/ts/docs/help/onboarding.ts
=> text for different platforms

src/ts/component/menu/smile.tsx
=> fix active tab in MenuSmile

src/ts/component/block/dataview/cell/object.tsx, src/ts/component/menu/block/add.tsx, src/ts/component/menu/block/link.tsx, src/ts/component/menu/block/mention.tsx, src/ts/component/menu/block/more.tsx, src/ts/component/menu/dataview/object/list.tsx, src/ts/component/menu/search/object.tsx, src/ts/component/page/main/create.tsx, src/ts/component/popup/page/settings/personal.tsx, src/ts/component/util/graph.tsx, src/ts/component/widget/index.tsx, src/ts/lib/api/command.ts, src/ts/lib/api/mapper.ts, src/ts/lib/keyboard.ts, src/ts/lib/util/data.ts, src/ts/lib/util/object.ts
=> Feature/JS-4455: BlockLink default settings in UtilObject.create

src/json/text.json, src/scss/popup/settings.scss
=> Feature/JS-4409: Email opening fix

src/json/constant.json, src/ts/component/block/dataview/view/graph.tsx, src/ts/component/header/main/graph.tsx, src/ts/component/menu/dataview/view/layout.tsx, src/ts/component/menu/graph/settings.tsx, src/ts/component/page/main/graph.tsx, src/ts/component/util/graph.tsx, src/ts/store/common.ts
=> Feature/JS-4482: Rework graph settings

src/ts/lib/api/dispatcher.ts, src/ts/lib/api/mapper.ts, src/ts/lib/api/response.ts
=> JS-4483: Events mapping

electron/js/menu.js, src/ts/component/popup/page/membership/paid.tsx
=> GO-3466: Pay with crypto button

src/ts/component/block/dataview.tsx, src/ts/component/block/relation.tsx, src/ts/component/menu/block/relation/view.tsx, src/ts/lib/analytics.ts
=> Analytics/JS-4607: Change event key when changing name

src/scss/block/dataview.scss, src/scss/component/dragLayer.scss, src/scss/menu/dataview/text.scss, src/ts/component/block/dataview/cell/index.tsx, src/ts/model/block.ts
=> Feature/JS-4558: Remove set bg

src/ts/component/editor/page.tsx, src/ts/component/form/input.tsx, src/ts/lib/storage.ts
=> Bugfix/JS-4490: Editor keys when search is open

src/scss/common.scss, src/scss/theme/dark/common.scss, src/ts/component/menu/search/text.tsx, src/ts/lib/util/common.ts
=> Refactoring of search tag

src/ts/component/editor/page.tsx
---
---
This PR fixes a bug where copying and pasting text into anytype's code blocks from Windows results in an extra blank line due to the \r\n newlines being interpreted as two newline characters.
None.
=> fix normalize line endings to handle Windows clipboard \r\n issue

src/json/text.json, src/scss/popup/membership.scss, src/ts/component/popup/page/membership/current.tsx, src/ts/component/popup/page/membership/paid.tsx
=> Feature/JS-4637: Disclamer and acquired on other platform logic

src/json/text.json, src/ts/component/header/main/object.tsx, src/ts/component/list/objectManager.tsx, src/ts/component/list/widget.tsx, src/ts/component/menu/object.tsx, src/ts/component/page/main/archive.tsx, src/ts/lib/action.ts
=> Feature/JS-4262: Bin in read-only space

src/ts/docs/help/whatsNew.ts
---
-  Edits & Revisions
-  Added bullet about new version history
=> Update Release Notes 4.5.ts

src/ts/lib/util/common.ts
=> fix(util): Accept email TLDs up to 12 characters

src/json/survey.json, src/json/text.json, src/ts/interface/common.ts, src/ts/lib/survey.ts, src/ts/lib/util/data.ts
=> Feature/JS-4713: Multiplayer survey

electron/js/util.js, src/json/constant.json
=> Enable be-BY

src/scss/popup/search.scss
=> Feature/JS-4754: Search popup width fix

src/ts/component/popup/page/membership/paid.tsx
=> Feature/JS-4499: do not check name if tier does not feature it

src/ts/component/menu/space.tsx, src/ts/component/popup/page/settings/space/index.tsx, src/ts/lib/util/space.ts
=> Create space when you click on Share space in personal

src/scss/list/widget.scss, src/ts/component/list/widget.tsx, src/ts/component/menu/widget.tsx, src/ts/component/widget/index.tsx, src/ts/lib/action.ts, src/ts/lib/util/menu.ts
=> Feature/JS-4766: Widget adding UX

src/scss/menu/syncStatus.scss, src/ts/component/menu/syncStatus.tsx
=> Feature/JS-4835: Restrictions check for objects in sync menu

src/ts/component/block/chat/message/index.tsx, src/ts/component/block/index.tsx, src/ts/component/block/text.tsx, src/ts/interface/block/index.ts, src/ts/lib/util/data.ts
=> JS-4524: Move render methods

src/json/text.json, src/scss/popup/membership.scss, src/ts/component/index.tsx, src/ts/component/popup/page/membership/paid.tsx
=> Feature/JS-4829: Membership handle crypto purchases

src/ts/component/block/embed.tsx, src/ts/component/index.tsx, src/ts/component/util/media/mermaid.tsx
=> Bugfix/JS-4896: Mermaid rendering

src/ts/component/menu/widget.tsx, src/ts/component/widget/index.tsx, src/ts/component/widget/view/index.tsx, src/ts/component/widget/view/list/index.tsx, src/ts/lib/util/menu.ts
=> Revert widget layout options

src/ts/docs/help/whatsNew.ts
---
Changes to Title and Feature Description
=> Update Whats New 6.ts

src/json/text.json, src/scss/block/chat.scss, src/ts/component/block/chat.tsx, src/ts/component/block/chat/message/index.tsx
=> Feature/JS-4873: Message editing

src/ts/component/block/chat.tsx, src/ts/component/block/chat/buttons.tsx
=> Feature/JS-4890: Chat buttons refactoring

src/json/route.ts, src/ts/component/page/index.tsx, src/ts/component/page/main/membership.tsx, src/ts/component/popup/membership.tsx, src/ts/lib/util/data.ts, src/ts/store/auth.ts
=> JS-4920: Membership tier deeplinks

src/ts/component/drag/provider.tsx, src/ts/component/list/widget.tsx, src/ts/component/menu/dataview/context.tsx, src/ts/component/menu/object.tsx, src/ts/component/menu/widget.tsx, src/ts/lib/action.ts, src/ts/lib/analytics.ts
=> Feature/JS-4921: Widget analytics route property

src/ts/component/form/filter.tsx, src/ts/component/popup/search.tsx
=> Feature/JS-4970: Search save

src/json/size.ts, src/ts/component/popup/page/settings/personal.tsx, src/ts/lib/keyboard.ts, src/ts/lib/sidebar.ts, src/ts/store/common.ts
=> JS-4986: Return auto sidebar logic

src/ts/component/widget/index.tsx
=> Bugfix/JS-4911: Fallback for widget layout when it does not match options

src/img/arrow/widgetGallery.svg, src/scss/widget/view/gallery.scss, src/ts/component/widget/view/gallery/index.tsx
=> Feature/JS-5006: Gallery view update

src/ts/component/widget/tree/index.tsx, src/ts/lib/action.ts
=> Bugfix/JS-5024: Reinit links tree when links change

src/ts/component/editor/page.tsx, src/ts/interface/common.ts, src/ts/lib/focus.ts, src/ts/lib/storage.ts
=> Feature/JS-4192: Save and restore focus on object close/open

src/ts/component/block/text.tsx, src/ts/component/form/pin.tsx
=> Fix markdown for divs

.github/workflows/build.yml
=> .github/workflows/build.yml refactoring publish-releases upload url

electron/js/menu.js, src/json/text.json, src/ts/component/block/text.tsx, src/ts/component/editor/page.tsx
=> Feature/JS-5020: Plain paste

src/ts/component/block/dataview.tsx, src/ts/component/block/relation.tsx, src/ts/component/menu/block/relation/view.tsx, src/ts/component/popup/relation.tsx, src/ts/component/sidebar/index.tsx, src/ts/lib/analytics.ts, src/ts/lib/api/command.ts
=> Feature/JS-5076: Batch editing update

src/ts/component/block/dataview/view/calendar.tsx, src/ts/component/block/dataview/view/calendar/item.tsx, src/ts/component/menu/dataview/calendar/day.tsx, src/ts/lib/analytics.ts
=> Feature/JS-5035: Create object in calendar view

src/ts/component/block/dataview/view/calendar/item.tsx
=> Feature/JS-5035: Calendar object creation isAllowedObject check

src/img/theme/dark/icon/menu/syncStatus/loading.svg, src/scss/theme/dark/menu.scss
=> Feature/JS-5152: Syncing icon in dark mode

src/ts/component/popup/page/membership/paid.tsx
=> membership: allow to buy subscription again after cancelling

src/ts/component/block/chat.tsx, src/ts/component/block/chat/form.tsx
=> Feature/JS-5228: Separate chat form

src/json/text.json, src/ts/component/popup/membership/finalization.tsx, src/ts/component/popup/page/membership/paid.tsx, src/ts/component/popup/page/settings/membership.tsx
=> Refactoring/JS-5304: parse periodType

src/ts/component/block/chat.tsx, src/ts/component/block/dataview/cell/text.tsx, src/ts/component/menu/dataview/date.tsx, src/ts/component/menu/item/vertical.tsx, src/ts/component/page/main/relation.tsx, src/ts/component/page/main/type.tsx, src/ts/component/popup/page/settings/space/index.tsx, src/ts/component/popup/page/usecase/item.tsx, src/ts/component/util/navigation.tsx, src/ts/lib/util/date.ts, src/ts/lib/util/menu.ts
=> Feature/JS-5173: Date as an object

src/json/constant.ts, src/ts/component/page/auth/login.tsx, src/ts/component/popup/page/settings/personal.tsx, src/ts/lib/util/data.ts
=> Feature/JS-5389: Share hint timing and settings analytics

src/json/text.json, src/scss/block/chat/message.scss, src/ts/component/block/chat.tsx, src/ts/component/block/chat/form.tsx, src/ts/component/block/chat/message/index.tsx
=> Feature/JS-5405: Replies with media

src/ts/component/page/main/archive.tsx, src/ts/component/sidebar/object.tsx
=> Feature/JS-5426: All content analytics

src/img/arrow/chatFormAttachment.svg, src/img/theme/dark/arrow/chatFormAttachment.svg, src/scss/block/chat/form.scss, src/scss/theme/dark/block.scss, src/ts/component/block/chat/form.tsx
=> Feature/JS-5303: Swiper in form attachments

electron/js/menu.js
(reopened with proper branch name)
=> linux, fix menu visibility toggle

src/scss/component/share.scss, src/ts/lib/util/data.ts
=> Feature/JS-5507: Shared spaces tooltip logic update

src/ts/component/menu/help.tsx, src/ts/component/page/auth/onboard.tsx
=> Feature/JS-5648: Hide "show hints" button

src/img/theme/dark/icon/widget/remove.svg, src/scss/component/share.scss, src/scss/theme/dark/common.scss, src/scss/theme/dark/widget.scss, src/scss/widget/common.scss
=> Feature/JS-5499: Icon close update

src/ts/component/popup/invite/confirm.tsx
=> Add preloader to invite confirm

src/ts/docs/help/onboarding.ts
=> Feature/JS-5677: Onboarding widget fix

src/ts/component/sidebar/object.tsx
=> Design/JS-5675: Tab specific default view

src/scss/block/dataview/view/grid.scss, src/ts/component/block/dataview/view/grid.tsx, src/ts/component/block/dataview/view/grid/head/row.tsx
=> JS-5709: fixed set header

src/ts/component/popup/page/settings/space/list.tsx, src/ts/lib/util/space.ts
=> Fix space filters

src/scss/block/featured.scss
=> Bugfix/JS-3496: Featured relations rework

src/ts/component/form/button.tsx, src/ts/component/form/drag/vertical.tsx, src/ts/component/form/input.tsx, src/ts/component/form/inputWithFile.tsx, src/ts/component/page/auth/onboard.tsx
=> Refactoring/JS-4200: Functional components

src/json/text.json, src/scss/block/dataview/view/grid.scss, src/ts/component/block/dataview/view/grid.tsx, src/ts/component/block/dataview/view/grid/foot/cell.tsx, src/ts/component/block/dataview/view/grid/foot/row.tsx, src/ts/component/block/dataview/view/grid/head/cell.tsx, src/ts/component/block/dataview/view/grid/head/row.tsx, src/ts/component/popup/search.tsx, src/ts/interface/block/dataview.ts, src/ts/interface/common.ts, src/ts/lib/api/mapper.ts, src/ts/lib/dataview.ts, src/ts/lib/relation.ts, src/ts/lib/util/menu.ts, src/ts/model/viewRelation.ts
=> Feature/JS-5797: Calculations

src/json/constant.ts, src/ts/component/block/chat.tsx, src/ts/component/block/chat/message/index.tsx, src/ts/component/block/chat/message/reply.tsx, src/ts/interface/block/chat.ts
=> Feature/JS-5412: Scroll to reply

src/json/text.json, src/scss/component/emailCollectionForm.scss, src/ts/component/form/input.tsx, src/ts/component/util/emailCollectionForm.tsx
=> Feature/JS-5871: Email collection form updates

src/ts/component/menu/block/relation/edit.tsx, src/ts/component/menu/dataview/relation/edit.tsx, src/ts/interface/block/dataview.ts, src/ts/lib/api/mapper.ts, src/ts/model/viewRelation.ts
=> Clean up relation date settings

src/ts/component/menu/object.tsx, src/ts/component/page/index.tsx, src/ts/component/page/main/object.tsx, src/ts/lib/storage.ts
=> Feature/JS-5534: Add invite to object link

src/ts/app.tsx, src/ts/component/menu/help.tsx, src/ts/component/page/auth/login.tsx, src/ts/component/util/marker.tsx, src/ts/component/util/media/mermaid.tsx, src/ts/component/util/share/tooltip.tsx, src/ts/component/util/sync.tsx, src/ts/lib/preview.ts, src/ts/store/common.ts
=> JS-4200: ShareTooltip as functional component + refactoring

src/json/text.json, src/ts/component/header/main/history.tsx, src/ts/component/header/main/object.tsx, src/ts/component/menu/dataview/view/settings.tsx
=> JS-4200: HeaderMainHistory as functional component

dist/workers/graph.js, src/scss/block/dataview/view/graph.scss, src/scss/page/main/graph.scss, src/scss/widget/view/graph.scss, src/ts/component/graph/provider.tsx, src/ts/component/page/main/chat.tsx, src/ts/lib/util/common.ts, src/ts/store/common.ts
=> Refactoring/JS-4200: GraphProvider as functional component

src/json/url.ts, src/ts/app.tsx, src/ts/lib/survey.ts, src/ts/lib/util/data.ts
=> Feature/JS-5801: PMF-2

src/scss/page/main/date.scss, src/ts/component/page/main/date.tsx
=> Feature/JS-5920: day name

src/ts/component/page/main/date.tsx
=> GO-4670 Add complex filter on lastModifiedDate

src/json/text.json, src/ts/component/menu/block/relation/view.tsx, src/ts/component/menu/dataview/object/values.tsx, src/ts/component/popup/relation.tsx, src/ts/component/sidebar/section/type/relation.tsx, src/ts/lib/relation.ts, src/ts/lib/util/data.ts, src/ts/store/record.ts
=> Feature/JS-5892: Conflict relations

src/scss/block/chat/attachment.scss
=> Feature/JS-5752: Bookmark description color

update.sh
---
---
This PR updates the `update.sh` script to support both `macos-13` and `macos-latest` flags, ensuring compatibility with existing usage and alignment with the `README`.
https://github.com/anyproto/anytype-ts/issues/1113
=> Update update.sh to support both "macos-13" and "macos-latest" flags

electron/js/server.js
test with https://github.com/anyproto/anytype-heart/pull/1976
=> send shutdown to stdin instead of os signal(kill) on windows

src/ts/component/block/dataview.tsx, src/ts/component/graph/provider.tsx, src/ts/component/header/main/graph.tsx, src/ts/component/page/main/graph.tsx
=> Refactoring/JS-5938: Graph.setRootId

src/img/icon/popup/confirm/warningInverted.svg, src/json/text.json, src/scss/block/chat/form.scss, src/scss/popup/confirm.scss, src/ts/component/block/chat/form.tsx
=> Feature/JS-5168: Chat limits

src/scss/block/chat/message.scss
=> Feature/JS-5810: Expand message with reply

src/ts/lib/util/common.ts
=> Feature/JS-6071: Urls in chat

src/scss/block/text.scss, src/ts/component/block/text.tsx, src/ts/lib/keyboard.ts
=> Feature/JS-4030: RTL

src/ts/component/menu/block/add.tsx, src/ts/component/menu/item/vertical.tsx, src/ts/component/menu/relation/suggest.tsx, src/ts/component/menu/search/object.tsx, src/ts/component/menu/select.tsx, src/ts/component/menu/syncStatus.tsx, src/ts/component/menu/type/suggest.tsx, src/ts/interface/menu.ts, src/ts/lib/util/data.ts
=> Refactoring/JS-5926: Menu section

src/img/arrow/existing.svg, src/json/menu.ts, src/json/text.json, src/scss/menu/icon.scss, src/ts/component/block/dataview.tsx, src/ts/component/menu/dataview/new.tsx, src/ts/component/menu/dataview/template/list.tsx, src/ts/component/menu/index.tsx
=> Feature/JS-6012: Add existing object to collection

src/ts/component/header/main/object.tsx, src/ts/component/menu/publish.tsx
=> Feature/JS-6025: Web publish analytics

src/json/text.json, src/scss/component/sidebar/page.scss, src/scss/component/sidebar/page/object.scss, src/ts/component/sidebar/page/object/relation.tsx
=> Feature/JS-6166: Local fields description (question icon)

electron.js, electron/js/preload.js, package.json, src/ts/component/popup/spaceCreate.tsx, src/ts/component/util/progress.tsx, src/ts/component/vault/index.tsx, src/ts/component/vault/item.tsx, src/ts/lib/sidebar.ts, src/ts/lib/storage.ts, src/ts/lib/util/menu.ts, src/ts/lib/util/space.ts, src/ts/store/auth.ts, src/ts/store/common.ts
=> Refactoring/JS-6181: Storage

src/json/text.json, src/scss/component/sidebar/page/object.scss, src/scss/component/sidebar/page/type.scss, src/ts/component/sidebar/page/object/relation.tsx, src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/section/index.tsx, src/ts/component/sidebar/section/object/relation.tsx, src/ts/component/sidebar/section/type/conflict.tsx, src/ts/component/sidebar/section/type/relation.tsx, src/ts/lib/api/command.ts, src/ts/lib/api/response.ts
=> Feature/JS-6044: Conflict relation on type level

src/json/text.json, src/scss/popup/settings.scss, src/ts/component/menu/publish.tsx, src/ts/component/popup/page/settings/data/index.tsx, src/ts/component/popup/page/settings/data/publish.tsx, src/ts/component/popup/page/settings/delete.tsx, src/ts/component/popup/page/settings/membership.tsx, src/ts/component/popup/page/settings/space/list.tsx, src/ts/component/popup/search.tsx, src/ts/component/popup/settings.tsx, src/ts/lib/util/space.ts
=> Feature/JS-6209: Published list

electron/js/api.js, electron/js/window.js, src/ts/lib/api/dispatcher.ts, src/ts/lib/api/mapper.ts
=> Feature/JS-6208: Hide challenge integration

src/json/url.ts, src/ts/lib/api/command.ts
=> Integrate json api address

src/json/url.ts
middleware pr: https://github.com/anyproto/anytype-heart/pull/2045
=> use any.org domain for publishing

src/ts/component/popup/settings/onboarding.tsx
---
---
Currently you can select only `yml` as self-hosted config. Add `yaml` will be a good option because this is also recommend extension.
https://yaml.org/faq.html
=> Allow both 'yml' and 'yaml' file

src/ts/component/popup/page/settings/data/index.tsx, src/ts/component/popup/page/settings/data/publish.tsx, src/ts/interface/publish.ts, src/ts/lib/api/mapper.ts
=> Feature/JS-6345: Publishing filter

src/ts/component/menu/search/object.tsx, src/ts/component/sidebar/page/widget.tsx, src/ts/component/widget/space.tsx, src/ts/lib/util/menu.ts
=> Feature/JS-6274: Select type for widget source

src/scss/widget/space.scss
=> Feature/JS-6211: Space panel design review

src/scss/widget/space.scss
=> Feature/JS-6379: Plus button style

dist/workers/graph.js, src/ts/component/graph/provider.tsx
---
---
Hey there! I added a drag-to-select feature to the graph page because grabbing a whole bunch at once is so much easier! 😊
https://github.com/user-attachments/assets/a037e0a0-fbe1-4991-a5fa-f74ab64310bd
=> drag-to-select in graph page

src/ts/component/header/main/graph.tsx
---
---
Just noticed a missing semicolon while going through some code.
=> fix formatting

src/ts/component/selection/provider.tsx
---
---
This commit addresses the following issues:  
1. The Drag-To-Select box was not displaying in sets and collections.  
https://github.com/user-attachments/assets/ba0c56b2-3347-408d-a4d3-23c1c9493c9c
2. I noticed that the selection box only appears when selecting at least two nodes. Was this intentional? Additionally, when holding the Ctrl key, the box appears immediately even with just one selection.  
https://github.com/user-attachments/assets/be82ae22-676d-42b9-8fe9-2e0dd19a597c
I'm not entirely sure about the design of the `checkNodes` function, so this commit is just a test. If you think keeping the Drag-To-Select box always visible would be a better approach, please let me know how I should adjust the implementation.  
I've attached a video showing the behavior after my …
=> Drag to select box display issues

src/scss/menu/common.scss, src/scss/menu/dataview/common.scss, src/ts/component/block/dataview/head.tsx, src/ts/component/block/dataview/view/grid/foot/cell.tsx, src/ts/component/block/featured.tsx, src/ts/component/block/table.tsx, src/ts/component/menu/block/action.tsx, src/ts/component/menu/block/add.tsx, src/ts/component/menu/block/layout.tsx, src/ts/component/menu/block/link/settings.tsx, src/ts/component/menu/block/mention.tsx, src/ts/component/menu/block/relation/edit.tsx, src/ts/component/menu/dataview/context.tsx, src/ts/component/menu/dataview/filter/values.tsx, src/ts/component/menu/dataview/object/values.tsx, src/ts/component/menu/dataview/option/list.tsx, src/ts/component/menu/dataview/relation/edit.tsx, src/ts/component/menu/dataview/template/context.tsx, src/ts/component/menu/dataview/template/list.tsx, src/ts/component/menu/dataview/view/layout.tsx, src/ts/component/menu/index.tsx, src/ts/component/menu/object.tsx, src/ts/component/menu/relation/suggest.tsx, src/ts/component/menu/smile.tsx, src/ts/component/menu/type/suggest.tsx, src/ts/interface/menu.ts
=> Rework menu keyboard rebinding

extension/popup/create.tsx, extension/scss/popup.scss, src/ts/component/block/bookmark.tsx, src/ts/component/block/chat/form.tsx, src/ts/component/editor/page.tsx, src/ts/component/menu/dataview/create/bookmark.tsx, src/ts/lib/api/command.ts, src/ts/lib/util/menu.ts
=> Feature/JS-6448: Bookmark templateId integration

src/json/lang.ts
=> Enable fa-IR

src/json/text.json, src/scss/list/object.scss, src/ts/component/menu/block/layout.tsx, src/ts/component/page/elements/head/controlButtons.tsx, src/ts/lib/util/object.ts
=> Feature/JS-6011: Layout conflict

dist/embed/iframe.html, src/json/text.json, src/ts/component/menu/dataview/calendar.tsx, src/ts/component/page/main/settings/language.tsx, src/ts/lib/action.ts, src/ts/lib/util/date.ts, src/ts/store/common.ts
=> Feature/JS-6133: First day of the week setting

electron/js/api.js, electron/js/menu.js, src/json/text.json, src/scss/popup/confirm.scss, src/ts/lib/keyboard.ts
=> Feature/JS-6439: Update channel alert

src/ts/component/block/dataview/view/calendar/item.tsx, src/ts/component/header/main/object.tsx, src/ts/component/page/main/settings/language.tsx, src/ts/lib/util/data.ts
=> Bugfix/JS-6386: Template counter

src/scss/block/dataview/view/calendar.scss, src/ts/component/block/dataview/view/calendar/item.tsx
=> Feature/JS-6443: Add plus to calendar

src/ts/component/block/text.tsx, src/ts/component/menu/block/add.tsx
=> Feature/JS-6242: Markdown link

src/scss/theme/dark/common.scss, src/scss/theme/dark/page.scss
=> Feature/JS-6513: Space settings dark mode

src/json/text.json, src/ts/component/page/main/settings/account.tsx, src/ts/interface/account.ts, src/ts/lib/api/mapper.ts, src/ts/model/account.ts
=> JS-6493: add Ethereum Address to Profile

src/json/text.json, src/scss/component/sidebar/preview.scss, src/scss/page/main/media.scss, src/ts/component/page/main/media.tsx, src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/preview.tsx
=> Feature/JS-6165: Edit file types

src/json/text.json, src/scss/component/icon.scss, src/scss/component/sidebar/settings.scss, src/scss/menu/icon.scss, src/scss/widget/common.scss, src/scss/widget/tree.scss, src/scss/widget/view/common.scss, src/ts/component/widget/index.tsx, src/ts/component/widget/tree/index.tsx, src/ts/component/widget/tree/item.tsx
=> Feature/JS-6543: Widget header update

src/ts/component/form/emailCollection.tsx, src/ts/component/menu/block/layout.tsx, src/ts/component/sidebar/page/object/relation.tsx, src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/page/widget.tsx, src/ts/component/sidebar/section/type/relation.tsx, src/ts/component/sidebar/section/type/title.tsx, src/ts/interface/common.ts, src/ts/lib/analytics.ts, src/ts/lib/util/object.ts
=> Feature/JS-6518: Analytics on type editing

src/json/relation.ts, src/json/text.json, src/scss/component/sidebar/page/type.scss, src/ts/component/block/dataview/head.tsx, src/ts/component/graph/provider.tsx, src/ts/component/header/main/graph.tsx, src/ts/component/menu/item/vertical.tsx, src/ts/component/menu/search/object.tsx, src/ts/component/page/elements/head/simple.tsx, src/ts/component/page/main/navigation.tsx, src/ts/component/popup/search.tsx, src/ts/component/sidebar/page/object/relation.tsx, src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/page/widget.tsx, src/ts/component/sidebar/section/type/title.tsx, src/ts/component/util/object/name.tsx, src/ts/component/widget/index.tsx, src/ts/interface/common.ts, src/ts/interface/menu.ts, src/ts/lib/util/data.ts, src/ts/store/detail.ts
=> Feature/JS-6579: Plural type names

src/json/shortcut.ts
=> Feature/JS-6669: Shortcut name fix

src/img/icon/payment/ice.svg, src/scss/page/main/settings.scss, src/scss/popup/membership.scss, src/ts/component/page/main/settings/membership.tsx, src/ts/model/membershipTier.ts
=> Feature/JS-6614: New tier

src/json/text.json, src/scss/page/auth.scss, src/ts/component/page/auth/migrate.tsx, src/ts/lib/api/response.ts
=> Feature/JS-6586: Not enough space error

src/json/text.json, src/scss/page/main/settings.scss, src/ts/component/page/main/settings/space/index.tsx, src/ts/component/page/main/settings/space/share.tsx, src/ts/component/sidebar/page/settings/index.tsx, src/ts/component/widget/space.tsx
=> Feature/JS-6713: Space settings state

src/ts/component/page/main/settings/space/index.tsx
=> Feature/JS-6453: Settings space general and empty page logic

src/scss/component/editor.scss
=> Feature/JS-6519: Object controls position

src/ts/component/sidebar/page/settings/library.tsx, src/ts/lib/analytics.ts
=> Feature/JS-6170: Library context click

src/ts/component/page/elements/head/simple.tsx, src/ts/lib/util/object.ts
=> Feature/JS-6650: Templates menu empty state fix

src/json/text.json, src/scss/component/icon.scss, src/scss/page/main/settings.scss, src/scss/theme/dark/common.scss, src/ts/component/page/main/settings/space/index.tsx, src/ts/component/page/main/settings/space/storage.tsx, src/ts/component/sidebar/page/settings/index.tsx
=> Feature/JS-6678: Space settings design review

src/ts/component/menu/type/suggest.tsx, src/ts/lib/storage.ts, src/ts/lib/util/menu.ts
=> Feature/JS-6657: Types dnd

src/img/icon/toast/check.svg, src/json/text.json, src/scss/component/toast.scss, src/ts/component/util/toast.tsx, src/ts/interface/common.ts, src/ts/lib/api/dispatcher.ts, src/ts/lib/api/mapper.ts, src/ts/lib/preview.ts
=> Feature/JS-6606: Widget toast event

src/json/text.json
=> add web publishing limits info text.json

src/scss/component/header.scss, src/scss/menu/common.scss, src/scss/menu/identity.scss, src/ts/component/header/main/settings.tsx, src/ts/component/menu/identity.tsx, src/ts/component/menu/index.tsx
=> Feature/JS-6728: Identity menu

src/ts/component/page/auth/migrate.tsx
=> Feature/JS-6586: Migration screen error fix

src/ts/component/menu/identity.tsx, src/ts/component/menu/publish.tsx
=> Feature/JS-6767: Open builder popup from upgrade incentives

src/json/text.json, src/scss/menu/icon.scss, src/ts/component/menu/object.tsx, src/ts/component/menu/publish.tsx
=> Feature/JS-6785: Menu object advanced

src/json/error.ts, src/json/text.json, src/ts/component/page/main/invite.tsx
=> Feature/JS-6705: HTTPS link errors handling 

src/ts/component/menu/object.tsx
=> Feature/JS-6785: Menu object copy link update

src/ts/component/block/chat.tsx
=> Feature/JS-6261: Chat counters

src/ts/component/sidebar/section/type/relation.tsx
=> Feature/JS-6855: Conflict relations dnd analytics

src/json/text.json, src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/preview.tsx, src/ts/component/sidebar/section/type/title.tsx, src/ts/component/util/object/type.tsx, src/ts/lib/util/object.ts, src/ts/store/detail.ts
=> Feature/JS-6876: Type creation flow update

src/ts/component/block/chat.tsx, src/ts/component/block/chat/form.tsx
=> Feature/JS-6865: Scroll to bottom

src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/section/type/title.tsx
=> Feature/JS-6891: Create object analytics

src/scss/block/chat/attachment.scss, src/scss/block/chat/message.scss, src/ts/component/block/chat/message/index.tsx, src/ts/component/block/chat/message/reply.tsx
=> Feature/JS-6528: Chat messages design review

src/json/text.json, src/scss/menu/select.scss, src/ts/component/block/chat.tsx
=> Feature/JS-6534: Chat message menu update

src/ts/component/block/chat.tsx, src/ts/component/block/chat/message/index.tsx, src/ts/interface/block/chat.ts
=> Feature/JS-6534: More button logic

src/ts/component/block/chat/form.tsx
=> Feature/JS-6205: Attachments limit logic

src/scss/block/chat/message.scss, src/ts/component/block/chat/message/index.tsx
=> Feature/JS-6863: New messages divider position

src/json/constant.ts, src/scss/block/chat/message.scss, src/ts/component/block/chat.tsx, src/ts/component/block/chat/form.tsx, src/ts/component/block/chat/message/index.tsx
=> Feature/JS-6913: Mentions counter

src/scss/menu/block/mention.scss, src/ts/component/block/chat/form.tsx, src/ts/component/menu/block/mention.tsx, src/ts/component/menu/item/vertical.tsx, src/ts/component/util/object/name.tsx, src/ts/interface/menu.ts
=> Feature/JS-5490: You in mention menu

src/scss/block/chat/message.scss
=> Feature/JS-6054: New messages divider fix

src/img/icon/onboarding/copy.svg, src/json/text.json, src/scss/form/button.scss, src/scss/form/phrase.scss, src/scss/page/auth.scss, src/ts/component/form/phrase.tsx, src/ts/component/page/auth/onboard.tsx, src/ts/component/page/auth/select.tsx, src/ts/component/popup/logout.tsx
=> Feature/JS-6992: New onboarding flow

src/ts/component/page/auth/login.tsx, src/ts/lib/api/dispatcher.ts, src/ts/lib/api/mapper.ts, src/ts/lib/api/response.ts, src/ts/lib/util/data.ts, src/ts/store/chat.ts
=> Sync chat previews

src/ts/component/menu/publish.tsx, src/ts/component/page/main/membership.tsx, src/ts/component/page/main/settings/membership.tsx, src/ts/component/page/main/settings/space/share.tsx, src/ts/component/popup/invite/confirm.tsx, src/ts/component/popup/membership/finalization.tsx, src/ts/component/popup/page/membership/current.tsx, src/ts/interface/payment.ts, src/ts/lib/api/dispatcher.ts, src/ts/lib/util/data.ts, src/ts/model/membership.ts, src/ts/model/membershipTier.ts
=> Updated membership plans logic

src/ts/component/block/chat.tsx, src/ts/component/block/chat/form.tsx
=> Feature/JS-6917: Messages improved highlight logic

src/ts/app.tsx, src/ts/docs/help/whatsNew.ts
=> Feature/Release notes 0.46.X

src/json/constant.ts
=> fix: mcp config

src/json/text.json, src/scss/block/common.scss, src/scss/block/dataview/view/timeline.scss, src/scss/common.scss, src/scss/widget/view/list.scss, src/ts/component/block/dataview.tsx, src/ts/component/block/dataview/controls.tsx, src/ts/component/block/dataview/view/calendar.tsx, src/ts/component/block/dataview/view/timeline.tsx, src/ts/component/menu/dataview/relation/edit.tsx, src/ts/component/menu/dataview/view/layout.tsx, src/ts/component/util/error.tsx, src/ts/interface/block/dataview.ts, src/ts/lib/api/dispatcher.ts, src/ts/lib/api/mapper.ts, src/ts/lib/dataview.ts, src/ts/lib/relation.ts, src/ts/lib/util/common.ts, src/ts/lib/util/date.ts, src/ts/lib/util/menu.ts, src/ts/model/view.ts
=> Feature/JS-3669: Timeline view

src/ts/component/block/chat.tsx, src/ts/component/block/chat/buttons.tsx
=> Feature/JS-7008: Chat analytics update

src/ts/component/block/dataview/view/timeline.tsx, src/ts/lib/api/mapper.ts
=> Feature/JS-3669: Timeline

src/ts/component/popup/space/joinByLink.tsx
=> Feature/Popup joinByLink get id fix

src/ts/store/auth.ts, src/ts/store/block.ts, src/ts/store/chat.ts, src/ts/store/common.ts, src/ts/store/detail.ts, src/ts/store/extension.ts, src/ts/store/menu.ts, src/ts/store/notification.ts, src/ts/store/popup.ts, src/ts/store/progress.ts, src/ts/store/record.ts
=> docs(store): add JSDoc comments to all public methods in store classes

src/ts/component/block/media/image.tsx, src/ts/interface/block/index.ts
=> Functional components

src/json/shortcut.ts, src/ts/component/block/table.tsx, src/ts/component/editor/page.tsx, src/ts/component/vault/index.tsx, src/ts/lib/keyboard.ts
=> Feature/JS-4328: Table row keyboard reorder

package.json, src/scss/widget/common.scss, src/ts/component/widget/index.tsx
=> Feature/JS-7171: Bookmark widget create

electron.js
=> Bugfix/JS-4052: Window focus issue

src/ts/component/form/editable.tsx
=> Bugfix/JS-2642: The input of Chinese selection will duplicate the text itself

src/scss/menu/dataview/option.scss, src/ts/component/menu/dataview/option/edit.tsx, src/ts/component/menu/dataview/option/list.tsx, src/ts/component/page/main/relation.tsx, src/ts/lib/util/object.ts
=> Feature/JS-6499: Relation page update bugfix

src/ts/component/menu/dataview/option/edit.tsx, src/ts/component/menu/dataview/option/list.tsx, src/ts/component/page/main/relation.tsx
=> Feature/JS-7153: Create option button state

src/json/text.json, src/scss/page/main/void.scss, src/ts/component/page/main/void.tsx
=> Feature/JS-7191: Create chat from pageMainVoid

src/json/constant.ts, src/json/text.json, src/scss/component/header.scss, src/scss/component/preview/object.scss, src/scss/component/sidebar/page/type.scss, src/ts/component/block/featured.tsx, src/ts/component/header/main/object.tsx, src/ts/component/menu/block/add.tsx, src/ts/component/menu/dataview/template/context.tsx, src/ts/component/menu/dataview/template/list.tsx, src/ts/component/menu/object.tsx, src/ts/component/page/elements/head/simple.tsx, src/ts/component/page/main/edit.tsx, src/ts/component/preview/object.tsx, src/ts/component/sidebar/page/object/relation.tsx, src/ts/component/sidebar/page/type.tsx, src/ts/component/sidebar/page/widget.tsx, src/ts/component/sidebar/section/index.tsx, src/ts/component/sidebar/section/type/template.tsx, src/ts/lib/util/object.ts
=> Feature/JS-7264: Templates in Sidebar

electron/js/api.js, extension/lib/util.ts, src/ts/app.tsx, src/ts/component/page/auth/login.tsx, src/ts/component/page/auth/setup.tsx, src/ts/lib/api/command.ts, src/ts/lib/util/data.ts, src/ts/store/auth.ts
=> Refactoring/JS-5814: Add token to WalletSessionCreate

src/scss/menu/dataview/create/bookmark.scss, src/ts/component/menu/dataview/create/bookmark.tsx, src/ts/component/page/elements/tableOfContents.tsx, src/ts/lib/util/menu.ts
=> Feature/JS-7169: Bookmark preview

src/scss/block/dataview/view/common.scss
=> Feature/JS-7371: Cell long text fix

src/scss/block/dataview/view/gallery.scss
=> Feature/JS-7534: Input size in dataview gallery card

src/scss/block/dataview/view/common.scss, src/scss/block/dataview/view/list.scss, src/ts/component/block/dataview/view/list/row.tsx, src/ts/component/cell/text.tsx
=> Feature/JS-7373: Edit mode fixes

src/json/text.json
---
---
This PR replaces the mention of Sets with Queries at `onboardingInlineSet1Description` in `text.json` to adhere to new terminology.
=> Onboarding text incorrectly mentions Sets in text.json

src/ts/component/cell/text.tsx
Revert changes in b66791c875575e7ea4dbf4302b1d687bfb579e7f to fix date entry.
Edited the revert to keep:
`inputRef.current.setRange(range.current || { from: length, to: length }, false);`
instead of previous:
inputRef.current.setRange(range.current || { from: length, to: length });
---
---
=> Revert changes to text.tsx to fix date entry

src/json/text.json, src/ts/app.tsx, src/ts/component/block/chat/form.tsx, src/ts/component/editor/page.tsx, src/ts/lib/keyboard.ts
=> Feature/JS-7038: Color menu

src/ts/component/block/chat.tsx, src/ts/component/block/chat/form.tsx
=> Feature/JS-7653: Scroll to bottom button removed if chat is empty

flake.lock, flake.nix
---
---
This fixes dev environment for me
Changes:
- added gitleaks - needed for pre-commit hooks
- added libgbm - required to run electron
- updated default SERVER_PORT as it's does not match default webpack port
- updated flake.lock
no
=> Updated flake file

src/json/text.json
=> Feature/JS-7329: Remote storage update

src/scss/menu/common.scss, src/scss/menu/tableOfContents.scss, src/ts/component/block/chat.tsx, src/ts/component/menu/tableOfContents.tsx, src/ts/store/menu.ts
=> Feature/JS-7595: Update menu hovers

src/ts/component/block/chat/attachment/index.tsx
=> Feature/JS-7037: Images blur logic

src/ts/component/header/main/settings.tsx
=> Feature/JS-7658: More menu in spaceIndexEmpty

src/ts/component/page/main/void.tsx
=> Bugfix/JS-7631: Switch space in void if its possible

src/ts/component/editor/page.tsx
=> Feature/JS-7586: Ability to keep writing after creating a Bookmark

electron/js/api.js, src/ts/app.tsx, src/ts/component/form/pin.tsx, src/ts/lib/util/data.ts, src/ts/store/common.ts
=> Feature/JS-6811: Rework pin-code on keychain

src/ts/component/page/main/settings/space/index.tsx
=> Feature/JS-7623: No invite buttons in personal space

src/ts/component/widget/index.tsx
=> Feature/JS-7562: Allowed view types for widget show all button

src/ts/component/menu/publish.tsx, src/ts/component/menu/syncStatus.tsx, src/ts/component/util/upsell/storage.tsx
=> do not show incentive banners outside of anytype network

src/scss/component/sidebar/page/widget.scss, src/scss/widget/view/common.scss, src/scss/widget/view/gallery.scss, src/ts/component/widget/index.tsx, src/ts/component/widget/view/gallery/index.tsx
=> Gallery widget virtualised list

src/json/text.json, src/scss/page/auth.scss, src/ts/component/page/auth/login.tsx, src/ts/component/page/auth/onboard.tsx, src/ts/store/common.ts
=> Feature/JS-7515: Onboarding fixes

src/scss/page/auth.scss, src/scss/theme/dark/page.scss
=> Feature/JS-7715: Onboarding design review

src/ts/component/menu/syncStatus.tsx, src/ts/component/page/main/settings/space/storage.tsx, src/ts/component/util/upsell/storage.tsx, src/ts/lib/analytics.ts
=> Feature/JS-7652: Analytics on storage incentives

.github/workflows/nightly.yml
=> OPS-780 part 2

README.md
Updated build instructions and clarified development workflow.
---
---
=> Revise build and development workflow instructions

src/ts/component/widget/tree/index.tsx
=> Feature/JS-7848: Widget preview filter

src/json/text.json
=> Feature/JS-7836: Typo fix

src/ts/component/page/auth/setup.tsx, src/ts/component/sidebar/left.tsx, src/ts/component/sidebar/page/vault.tsx, src/ts/lib/highlight.ts
=> Feature/JS-7867: Create space highlight

src/json/text.json, src/ts/component/page/main/settings/space/share.tsx, src/ts/component/page/main/settings/space/share/members.tsx
=> Feature/JS-7862: Stop sharing logic

src/ts/component/sidebar/section/type/template.tsx
=> fix template opening

src/json/text.json, src/scss/block/chat.scss, src/scss/component/editor.scss, src/scss/page/main/chat.scss, src/ts/component/block/chat.tsx, src/ts/component/menu/widget.tsx, src/ts/component/page/main/chat.tsx, src/ts/component/sidebar/page/vault.tsx, src/ts/component/widget/index.tsx, src/ts/component/widget/tree/index.tsx, src/ts/component/widget/view/index.tsx, src/ts/component/widget/view/list/index.tsx, src/ts/component/widget/view/list/item.tsx, src/ts/interface/account.ts, src/ts/interface/block/widget.ts, src/ts/lib/action.ts, src/ts/lib/api/mapper.ts, src/ts/lib/util/data.ts, src/ts/model/account.ts, src/ts/store/block.ts
=> Refactoring/JS-7982: Remove old dashboard logic

src/ts/component/page/main/settings/space/share.tsx
=> Feature/JS-7999: Disable sharing of new spaces if limit is reached

src/ts/docs/help/onboarding.ts, src/ts/lib/onboarding.ts
=> Feature/JS-7998:  Graph tooltip position

.github/workflows/build.yml, .github/workflows/nightly.yml, electron/js/preload.cjs, electron/preload.js, src/ts/app.tsx
=> OPS-824 added process.env.SENTRY_DSN
